### ISSUE TITLE
No captcha

### ISSUE THREAD

**Issue by Braveras** [w35l3y/userscripts#59] opened 2018-02-22 15:33 UTC
**Browser:** Firefox<br />
**Plugin:** Tampermonkey <br />
**Script:** Flash games (BETA)<br />
The captcha doesnt show up for setting the game score & ms so its impossible to start the script.

**Comment by w35l3y** [comment] 2018-02-22 16:05
Duplicate of #52

**Closed by w35l3y** 2018-02-22 16:05 UTC
